#!/usr/bin/env bash
# fix Ubuntu container's to listen on port 80

apt-get update
apt-get -y install curl
rm /etc/nginx/sites-available/*
rm /etc/nginx/sites-enabled/*~
sed -i "s/$8080/$80/" /etc/nginx/sites-enabled/default

service nginx restart
